# Generated by Django 5.2.1 on 2025-05-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
                ('projects', models.IntegerField()),
                ('years', models.IntegerField()),
                ('price', models.CharField(max_length=10)),
            ],
        ),
    ]
