# Generated by Django 5.2.1 on 2025-05-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
